version: '3'

services:
  app1:
    build:
      context: ./app1
    ports:
      - "5000:5000"

  app2:
    build:
      context: ./app2
    ports:
      - "5001:5000"

  app3:
    build:
      context: ./app3
    ports:
      - "5002:5000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"  # Port untuk mengakses Nginx di host

  prometheus:
    build:
      context: ./prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Pastikan file ini ada
    ports:
      - "9090:9090"  # Port untuk mengakses Prometheus di host

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  # Port untuk mengakses Grafana di host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Password default untuk admin
    volumes:
      - grafana-storage:/var/lib/grafana  # Penyimpanan data Grafana

volumes:
  grafana-storage:  # Volume untuk penyimpanan data Grafana

