version: "3.8"

services:
  app1:
    build:
      context: ./app1
    ports:
      - "5001:5000"
    environment:
      - APP_NUMBER=1
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      retries: 3

  app2:
    build:
      context: ./app2
    ports:
      - "5002:5000"
    environment:
      - APP_NUMBER=2
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      retries: 3

  app3:
    build:
      context: ./app3
    ports:
      - "5003:5000"
    environment:
      - APP_NUMBER=3
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      retries: 3

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_app_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9090:9090"
    depends_on:
      - app1
      - app2
      - app3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/config.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  mysql-data:
