<<<<<<< HEAD
version: "3.8"
=======
version: '3'
>>>>>>> 29b4750f76282410e5b7952fdb20a63756a5fc0e

services:
  app1:
    build:
      context: ./app1
<<<<<<< HEAD
      platforms:
        - linux/arm64
    ports:
      - "5001:5000"
    environment:
      - APP_NUMBER=1
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
=======
    ports:
      - "5000:5000"
>>>>>>> 29b4750f76282410e5b7952fdb20a63756a5fc0e

  app2:
    build:
      context: ./app2
<<<<<<< HEAD
      platforms:
        - linux/arm64
    ports:
      - "5002:5000"
    environment:
      - APP_NUMBER=2
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
=======
    ports:
      - "5001:5000"
>>>>>>> 29b4750f76282410e5b7952fdb20a63756a5fc0e

  app3:
    build:
      context: ./app3
<<<<<<< HEAD
      platforms:
        - linux/arm64
    ports:
      - "5003:5000"
    environment:
      - APP_NUMBER=3
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:8.0
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_app_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MYSQL_ROOT_PASSWORD",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
=======
    ports:
      - "5002:5000"
>>>>>>> 29b4750f76282410e5b7952fdb20a63756a5fc0e

  nginx:
    build:
      context: ./nginx
<<<<<<< HEAD
      platforms:
        - linux/arm64
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  prometheus:
    build:
      context: ./prometheus
      platforms:
        - linux/arm64
=======
    ports:
      - "8080:80"  # Port untuk mengakses Nginx di host

  prometheus:
    image: prom/prometheus:latest  # Menggunakan versi terbaru
>>>>>>> 29b4750f76282410e5b7952fdb20a63756a5fc0e
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
<<<<<<< HEAD
      - "9090:9090"
    depends_on:
      - app1
      - app2
      - app3

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  mysql-data:
=======
      - "9090:9090"  # Port untuk mengakses Prometheus di host

  grafana:
    image: grafana/grafana:latest  # Menggunakan versi terbaru
    ports:
      - "3000:3000"  # Port untuk mengakses Grafana di host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Password default untuk admin
    volumes:
      - grafana-storage:/var/lib/grafana  # Penyimpanan data Grafana
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  grafana-storage:  # Volume untuk penyimpanan data Grafana
>>>>>>> 29b4750f76282410e5b7952fdb20a63756a5fc0e
