version: "3.8"

services:
  app1:
    build:
      context: ./app1
      platforms:
        - linux/arm64
    ports:
      - "5001:5000"
    environment:
      - APP_NUMBER=1
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3

  app2:
    build:
      context: ./app2
      platforms:
        - linux/arm64
    ports:
      - "5002:5000"
    environment:
      - APP_NUMBER=2
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3

  app3:
    build:
      context: ./app3
      platforms:
        - linux/arm64
    ports:
      - "5003:5000"
    environment:
      - APP_NUMBER=3
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3

  db:
    image: mysql:8.0
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_app_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount init.sql here

  nginx:
    build:
      context: ./nginx
      platforms:
        - linux/arm64
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  prometheus:
    build:
      context: ./prometheus
      platforms:
        - linux/arm64
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    platform: linux/arm64
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  grafana-storage:
  mysql-data:
