services:
  app1: &app-template
    build:
      context: ./app1
      platforms:
        - linux/arm64
    ports:
      - "5001:5000"
    environment:
      - APP_NUMBER=1
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db
    depends_on:
      db:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app2:
    <<: *app-template
    build:
      context: ./app2
      platforms:
        - linux/arm64
    ports:
      - "5002:5000"
    environment:
      - APP_NUMBER=2
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db

  app3:
    <<: *app-template
    build:
      context: ./app3
      platforms:
        - linux/arm64
    ports:
      - "5003:5000"
    environment:
      - APP_NUMBER=3
      - DB_URI=mysql+mysqlconnector://flask_user:password@db/flask_app_db

  db:
    image: mysql:8.0
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_app_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    build:
      context: ./nginx
      platforms:
        - linux/arm64
    ports:
      - "8080:80"
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
      app3:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  prometheus:
    build:
      context: ./prometheus
      platforms:
        - linux/arm64
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "9090:9090"
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
      app3:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      prometheus:
        condition: service_started

volumes:
  grafana-storage:
  mysql-data:
