global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: "app1"
    static_configs:
      - targets: ["app1:5000"]

  - job_name: "app2"
    static_configs:
      - targets: ["app2:5000"]

  - job_name: "app3"
    static_configs:
      - targets: ["app3:5000"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:8080"]

  # Optional: Aggregate metrics from specific routes for each app
  - job_name: "flask_metrics"
    metrics_path: "/metrics/1"
    static_configs:
      - targets: ["app1:5000"]

  - job_name: "flask_metrics"
    metrics_path: "/metrics/2"
    static_configs:
      - targets: ["app2:5000"]

  - job_name: "flask_metrics"
    metrics_path: "/metrics/3"
    static_configs:
      - targets: ["app3:5000"]
