global:
  scrape_interval: 15s # How often to scrape targets by default

scrape_configs:
  - job_name: "flask_apps"
    scrape_interval: 15s # Override the default scrape interval if necessary
    static_configs:
      - targets:
          - "app1:5000"
          - "app2:5000"
          - "app3:5000"

  - job_name: "nginx"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "nginx:8080"
